---
# tasks file for users
- name: create new user
  user:
    name: user1
    generate_ssh_key: yes

- name: Set authorized key taken from file
  authorized_key:
    user: user1
    state: present
    key: "{{ lookup('file', '{{ public_ssh_key_path }}') }}"
